Repository apache/maven-resolver, pull requests merged in 2025-08, with the labels that each got.

#1534 Create missing output directory in CollectConfiguration
  maven-resolver-tools/src/main/java/org/eclipse/aether/tools/CollectConfiguration.java
Labels: maintenance

#1543 Add scope support for trusted checksums
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessor.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/resolution/TrustedChecksumsArtifactResolverPostProcessorTest.java
  src/site/markdown/configuration.md
Labels: enhancement

#1542 ConflictResolver improvements, preparations
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictIdSorter.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictMarker.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java
  maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/transformer/SimpleConflictMarker.java
Labels: enhancement

#1540 Ingest Maveniverse Heimdall
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceSupport.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/GroupTree.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/Node.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/ruletree/PrefixTree.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSourceTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSourceTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/RemoteRepositoryFilterSourceTestSupport.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/ruletree/GroupTreeTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/filter/ruletree/PrefixTreeTest.java
  maven-resolver-supplier-mvn3/pom.xml
  maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
  maven-resolver-supplier-mvn4/pom.xml
  maven-resolver-supplier-mvn4/src/main/java/org/eclipse/aether/supplier/RepositorySystemSupplier.java
  src/site/markdown/remote-repository-filtering.md
Labels: enhancement

#1544 Simplify filters
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/GroupIdRemoteRepositoryFilterSource.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/MetadataResolverSupplier.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/filter/PrefixesRemoteRepositoryFilterSource.java
Labels: enhancement

#1541 Resolver Thread management
  maven-resolver-connector-basic/src/main/java/org/eclipse/aether/connector/basic/BasicRepositoryConnector.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/DefaultMetadataResolver.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/collect/bf/BfDependencyCollector.java
  maven-resolver-util/pom.xml
  maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/ExecutorUtils.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/SmartExecutor.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/SmartExecutorUtils.java
  maven-resolver-util/src/main/java21/org/eclipse/aether/util/concurrency/SmartExecutorUtils.java
Labels: enhancement

#1553 SmartExecutor: on classic pools TCCL must be delegated
  maven-resolver-util/src/main/java/org/eclipse/aether/util/concurrency/SmartExecutor.java
Labels: bug

#1555 Profiling: most hot spots and possibly wasted thread.
  maven-resolver-api/src/main/java/org/eclipse/aether/scope/ScopeManager.java
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/scope/ScopeManagerImpl.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/version/GenericVersionScheme.java
Labels: enhancement

#1567 Restore ConflictResolver backward compatibility
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ClassicConflictResolver.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/PathConflictResolver.java
Labels: bug

#1568 Resolver 2 provides scope manager for mvn3
  maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/Maven3ScopeManagerConfiguration.java
  maven-resolver-supplier-mvn3/src/main/java/org/eclipse/aether/supplier/SessionBuilderSupplier.java
  maven-resolver-supplier-mvn3/src/test/java/org/eclipse/aether/supplier/RepositorySystemSupplierTest.java
Labels: enhancement

#1569 Restore ConfictResolver backward compatibility
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ClassicConflictResolver.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/PathConflictResolver.java
Labels: bug
