Repository apache/maven-resolver, pull requests merged in 2025-07, with the labels that each got.

#1515 Make rwlock-local the default
  maven-resolver-impl/src/main/java/org/eclipse/aether/internal/impl/synccontext/named/NamedLockFactoryAdapterFactoryImpl.java
Labels: enhancement

#1517 Ability to augment metadata nature for version range request
  maven-resolver-api/src/main/java/org/eclipse/aether/resolution/VersionRangeRequest.java
Labels: enhancement

#1524 Fix a few typos
  class-overview.svg
  maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/resolver/ResolverDemo.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/FileUtils.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictIdSorter.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/graph/transformer/ConflictResolver.java
  maven-resolver-util/src/main/java/org/eclipse/aether/util/repository/SimpleResolutionErrorPolicy.java
Labels: skip-changelog

#1525 Stop the container in the shutdown method
  maven-resolver-transport-minio/src/test/java/org/eclipse/aether/transport/minio/MinioTransporterIT.java
Labels: priority:blocker, skip-changelog

#1523 More semantic asserts
  maven-resolver-api/src/test/java/org/eclipse/aether/graph/DefaultDependencyNodeTest.java
  maven-resolver-connector-basic/src/test/java/org/eclipse/aether/connector/basic/ChecksumCalculatorTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultArtifactResolverTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultInstallerTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultMetadataResolverTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/DefaultUpdateCheckManagerTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/FileTrustedChecksumsSourceTestSupport.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/checksum/TrustedToProvidedChecksumsSourceAdapterTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/DependencyCollectorDelegateTestSupport.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/collect/bf/DependencyResolutionSkipperTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/BasedirNameMapperTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/GAVNameMapperTest.java
  maven-resolver-impl/src/test/java/org/eclipse/aether/internal/impl/synccontext/named/HashingNameMapperTest.java
  maven-resolver-named-locks/src/test/java/org/eclipse/aether/named/RetryTest.java
  maven-resolver-test-http/src/main/java/org/eclipse/aether/internal/test/util/http/HttpTransporterTest.java
  maven-resolver-util/src/test/java/org/eclipse/aether/util/StringDigestUtilTest.java
  maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/manager/DependencyManagerTest.java
  maven-resolver-util/src/test/java/org/eclipse/aether/util/graph/versions/ContextualSnapshotVersionFilterTest.java
Labels: skip-changelog

#1519 unused dependency
  maven-resolver-supplier/pom.xml
Labels: dependencies, skip-changelog
